### ISSUE TITLE
找不到GeneratedPluginRegistrant 

### ISSUE THREAD

**Issue by dqb101140127** [CrazyCoderShi/judou#1]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/13044675/51506364-09e3e980-1e27-11e9-839e-de2377df7b3c.png">

<img width="644" alt="image" src="https://user-images.githubusercontent.com/13044675/51506392-2122d700-1e27-11e9-98a7-8b2c6dbbd69b.png">

**Comment by CrazyCoderShi** [comment]
老铁，你的flutter没有安装好呀:joy:

**Comment by dqb101140127** [comment]
> 老铁，你的flutter没有安装好呀😂

😂好吧

**Comment by dqb101140127** [comment]
> > 老铁，你的flutter没有安装好呀😂
> 
> 😂好吧

<img width="556" alt="image" src="https://user-images.githubusercontent.com/13044675/51509702-1c651f80-1e35-11e9-9388-96a5c36f3aa0.png">
这个应该是装好了吧  还是报错

**Comment by CrazyCoderShi** [comment]
@dqb101140127 pod install 试试 ？
