### ISSUE TITLE
 Build failed with an exception.

### ISSUE THREAD

**Issue by Captain-Justin** [CrazyCoderShi/judou#2]
![image](https://user-images.githubusercontent.com/26615255/51965697-540f3f80-24a5-11e9-8556-f2f560c41f72.png)
我翻墙了也不行，这咋整啊

**Comment by CrazyCoderShi** [comment]
试试把源改到国内看看

**Comment by Captain-Justin** [comment]
在app/build.gradle添加compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }，然后保存UTF-8，就可以跑起来了。中间会有报错没包，多run几次，C:\Users\admin\.gradle\caches会有变大，基本就能跑通了
